### ISSUE TITLE
question: how does this relate to snap?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-probe#31]
I thought the raintank-probe was a snap plugin nowadays.
1) how does this project relate to the snap worldping plugin? where is the latter?
2) i did found https://github.com/raintank/snap-plugin-collector-ping but it only seems to do pings? is this for worldping, if so where's dns/http/.. ?
thanks

**Comment by woodsaj** [comment]
no snap yet.  The blocker for making raintank-collector a pure go binary was a lack of socket.io client library written in Go.   Someone has since written one, so we were able to just make the current probe architecture work.

Moving to Snap is still on the cards, we are just waiting for it to reach 1.0 status.
